

class utils():

    @staticmethod
    def get_punct():
        puncts = [',', '.', '"', ':', ')', '(', '-', '!', '?', '|', ';', "'", '$', '&', '/', '[', ']', '>', '%', '=',
                  '#', '*', '+', '\\', '•', '~', '@', '£',
                  '·', '_', '{', '}', '©', '^', '®', '`', '<', '→', '°', '€', '™', '›', '♥', '←', '×', '§', '″', '′',
                  'Â', '█', '½', 'à', '…', '\xa0', '\t',
                  '“', '★', '”', '–', '●', 'â', '►', '−', '¢', '²', '¬', '░', '¶', '↑', '±', '¿', '▾', '═', '¦', '║',
                  '―', '¥', '▓', '—', '‹', '─', '\u3000', '\u202f',
                  '▒', '：', '¼', '⊕', '▼', '▪', '†', '■', '’', '▀', '¨', '▄', '♫', '☆', 'é', '¯', '♦', '¤', '▲', 'è',
                  '¸', '¾', 'Ã', '⋅', '‘', '∞', '«',
                  '∙', '）', '↓', '、', '│', '（', '»', '，', '♪', '╩', '╚', '³', '・', '╦', '╣', '╔', '╗', '▬', '❤', 'ï',
                  'Ø', '¹', '≤', '‡', '√', '\x89', 'û', 'ì', 'å', 'ò']
        return puncts
    @staticmethod
    def get_lookup_dict():
        lookup_dict = {
            'abt': 'about',
            'afaik': 'as far as i know',
            'bc': 'because',
            'bfn': 'bye for now',
            'bgd': 'background',
            'bh': 'blockhead',
            'br': 'best regards',
            'btw': 'by the way',
            'cc': 'carbon copy',
            'chk': 'check',
            'dam': 'do not annoy me',
            'dd': 'dear daughter',
            'df': 'dear fiance',
            'ds': 'dear son',
            'dyk': 'did you know',
            'em': 'email',
            'ema': 'email address',
            'ftf': 'face to face',
            'fb': 'facebook',
            'ff': 'follow friday',
            'fotd': 'find of the day',
            'ftw': 'for the win',
            'fwiw': 'for what it is worth',
            'gts': 'guess the song',
            'hagn': 'have a good night',
            'hand': 'have a nice day',
            'hotd': 'headline of the day',
            'ht': 'heard through',
            'hth': 'hope that helps',
            'ic': 'i see',
            'icymi': 'in case you missed it',
            'idk': 'i do not know',
            'ig': 'instagram',
            'iirc': 'if i remember correctly',
            'imho': 'in my humble opinion',
            'imo': 'in my opinion',
            'irl': 'in real life',
            'iwsn': 'i want sex now',
            'jk': 'just kidding',
            'jsyk': 'just so you know',
            'jv': 'joint venture',
            'kk': 'cool cool',
            'kyso': 'knock your socks off',
            'lmao': 'laugh my ass off',
            'lmk': 'let me know',
            'lo': 'little one',
            'lol': 'laugh out loud',
            'mm': 'music monday',
            'mirl': 'meet in real life',
            'mrjn': 'marijuana',
            'nbd': 'no big deal',
            'nct': 'nobody cares though',
            'njoy': 'enjoy',
            'nsfw': 'not safe for work',
            'nts': 'note to self',
            'oh': 'overheard',
            'omg': 'oh my god',
            'oomf': 'one of my friends',
            'orly': 'oh really',
            'plmk': 'please let me know',
            'pnp': 'party and play',
            'qotd': 'quote of the day',
            're': 'in reply to in regards to',
            'rtq': 'read the question',
            'rt': 'retweet',
            'sfw': 'safe for work',
            'smdh': 'shaking my damn head',
            'smh': 'shaking my head',
            'so': 'significant other',
            'srs': 'serious',
            'tftf': 'thanks for the follow',
            'tftt': 'thanks for this tweet',
            'tj': 'tweetjack',
            'tl': 'timeline',
            'tldr': 'too long did not read',
            'tmb': 'tweet me back',
            'tt': 'trending topic',
            'ty': 'thank you',
            'tyia': 'thank you in advance',
            'tyt': 'take your time',
            'tyvw': 'thank you very much',
            'w': 'with',
            'wtv': 'whatever',
            'ygtr': 'you got that right',
            'ykwim': 'you know what i mean',
            'ykyat': 'you know you are addicted to',
            'ymmv': 'your mileage may vary',
            'yolo': 'you only live once',
            'yoyo': 'you are on your own',
            'yt': 'youtube',
            'yw': 'you are welcome',
            'zomg': 'oh my god to the maximum'
        }
        return lookup_dict
    @staticmethod
    def get_mispell_dict():
        mispell_dict = {"aren't": "are not",
                        "can't": "cannot",
                        "couldn't": "could not",
                        "couldnt": "could not",
                        "didn't": "did not",
                        "doesn't": "does not",
                        "doesnt": "does not",
                        "don't": "do not",
                        "hadn't": "had not",
                        "hasn't": "has not",
                        "haven't": "have not",
                        "havent": "have not",
                        "he'd": "he would",
                        "he'll": "he will",
                        "he's": "he is",
                        "i'd": "I would",
                        "i'd": "I had",
                        "i'll": "I will",
                        "i'm": "I am",
                        "isn't": "is not",
                        "it's": "it is",
                        "it'll": "it will",
                        "i've": "I have",
                        "let's": "let us",
                        "mightn't": "might not",
                        "mustn't": "must not",
                        "shan't": "shall not",
                        "she'd": "she would",
                        "she'll": "she will",
                        "she's": "she is",
                        "shouldn't": "should not",
                        "shouldnt": "should not",
                        "that's": "that is",
                        "thats": "that is",
                        "there's": "there is",
                        "theres": "there is",
                        "they'd": "they would",
                        "they'll": "they will",
                        "they're": "they are",
                        "theyre": "they are",
                        "they've": "they have",
                        "we'd": "we would",
                        "we're": "we are",
                        "weren't": "were not",
                        "we've": "we have",
                        "what'll": "what will",
                        "what're": "what are",
                        "what's": "what is",
                        "what've": "what have",
                        "where's": "where is",
                        "who'd": "who would",
                        "who'll": "who will",
                        "who're": "who are",
                        "who's": "who is",
                        "who've": "who have",
                        "won't": "will not",
                        "wouldn't": "would not",
                        "you'd": "you would",
                        "you'll": "you will",
                        "you're": "you are",
                        "you've": "you have",
                        "'re": " are",
                        "wasn't": "was not",
                        "we'll": " will",
                        "didn't": "did not"}
        return mispell_dict
